// Generated by CoffeeScript 1.6.3
(function() {
  var Game;

  Game = (function() {
    Game.DIM_X = 900;

    Game.DIM_Y = 900;

    function Game(ctx) {
      this.ctx = ctx;
      this.ship = null;
      this.asteroids = [];
      this.bullets = [];
    }

    Game.prototype.draw = function() {
      var asteroid, bullet, _i, _j, _len, _len1, _ref, _ref1, _results;
      this.ctx.clearRect(0, 0, this.DIM_X, this.DIM_Y);
      this.ship.draw(this.ctx);
      _ref = this.asteroids;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        asteroid = _ref[_i];
        asteroid.draw();
      }
      _ref1 = this.bullets;
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        bullet = _ref1[_j];
        _results.push(bullet.draw());
      }
      return _results;
    };

    return Game;

  })();

}).call(this);
