// Generated by CoffeeScript 1.6.3
(function() {
  var Ship,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Ship = (function(_super) {
    __extends(Ship, _super);

    Ship.RADIUS = 10;

    Ship.COLOR = "red";

    function Ship(pos, vel) {
      Ship.__super__.constructor.call(this, {
        pos: pos,
        vel: vel,
        radius: this.RADIUS,
        color: this.COLOR,
        wraps: true
      });
    }

    Ship.prototype.power = function(impulse) {
      this.vel.x += impulse.x * Math.cos(this.direction);
      return this.vel.y += impulse.y * Math.sin(this.direction);
    };

    Ship.prototype.draw = function(ctx) {
      var spaceship;
      spaceship = document.getElementById("spaceship");
      ctx.save();
      ctx.translate(this.pos.x, this.pos.y);
      ctx.rotate(this.direction - Math.PI / 2);
      ctx.translate(-this.pos.x, -this.pos.y);
      ctx.drawImage(spaceship, this.pos.x - 64, this.pos.y - 64);
      return ctx.restore();
    };

    Ship.prototype.move = function() {
      if (Math.abs(this.vel.x) > 0) {
        this.vel.x /= 1.02;
      }
      if (Math.abs(this.vel.y) > 0) {
        this.vel.y /= 1.02;
      }
      return Ship.__super__.move.apply(this, arguments);
    };

    return Ship;

  })(MovingObject);

}).call(this);
