// Generated by CoffeeScript 1.6.3
(function() {
  var Asteroid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Asteroid = (function(_super) {
    __extends(Asteroid, _super);

    Asteroid.RADIUS = 50;

    Asteroid.COLOR = "steelblue";

    function Asteroid(pos, vel) {
      Asteroid.__super__.constructor.call(this, {
        pos: pos,
        vel: vel,
        radius: this.RADIUS,
        color: this.COLOR,
        wraps: true
      });
    }

    Asteroid.prototype.randomAsteroid = function(dimX, dimY) {
      var pos, vel;
      pos = {
        x: Math.random() * dimX,
        y: Math.random() * dimY
      };
      vel = this.randomVec();
      return new Asteroid(pos, vel);
    };

    return Asteroid;

  })(MovingObject);

}).call(this);
