// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Asteroids.Bullet = (function(_super) {
    __extends(Bullet, _super);

    Bullet.RADIUS = 5;

    Bullet.COLOR = "yellow";

    Bullet.VELOCITY = {
      x: 10,
      y: 10
    };

    function Bullet(pos, dir) {
      this.dir = dir;
      Bullet.__super__.constructor.call(this, {
        pos: pos,
        vel: this.VELOCITY,
        radius: this.RADIUS,
        color: this.COLOR,
        wraps: false
      });
    }

    return Bullet;

  })(Asteroids.MovingObject);

}).call(this);
